Models/ThuongHieu.cs
using System.Collections.Generic;

namespace PhuKienDienThoai.Models
{
    public class ThuongHieu
    {
        public int Id { get; set; }
        public string TenThuongHieu { get; set; }
        public ICollection<SanPham> SanPhames { get; set; }
        public ThuongHieu()
        {
            SanPhames = new HashSet<SanPham>();
        }
    }
}

Controllers/ThuongHieuController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhuKienDienThoai.Data;
using X.PagedList;

namespace PhuKienDienThoai.Controllers
{
    public class ThuongHieuController : Controller
    {
        ApplicationDbContext context;
        public ThuongHieuController(ApplicationDbContext _context) => context = _context;
        [HttpGet("[Controller]/{id}")]
        public async Task<IActionResult> Index(int id, int? page)
        {
            var data = await context.SanPham
                                    .Include(x => x.ThuongHieu)
                                    .Where(x => x.ThuongHieu.Id == id)
                                    .ToListAsync();

            var ThuongHieu = await context.ThuongHieu.FindAsync(id);

            ViewData["HeadTitle"] = ThuongHieu.TenThuongHieu;
            ViewData["Title"] = "Sản phẩm theo thương hiệu " + ViewData["HeadTitle"];
            var model = data.ToPagedList(page ?? 1, 9);
            return View("Views/Home/Index.cshtml", model);
            // return View("Views/Home/Index.cshtml",data);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
                context.Dispose();
            base.Dispose(true);
        }
    }
}

Views/Shared/Components/ThuongHieu/Default.cshtml
@using PhuKienDienThoai.Models
@model List<ThuongHieu>
<div class="brands_products"><!--brands_products-->
    <h2 class="title text-center"><span class="text-block">Thương hiệu</span></h2>
    <div class="brands-name">
       
        <ul class="nav nav-pills nav-stacked">
            @foreach(var item in Model)
            {
                <li><a asp-action="Index" 
                        asp-controller="ThuongHieu" 
                        asp-route-id="@item.Id"> <span class="pull-right">(@item.SanPhames.Count())</span>@item.TenThuongHieu</a></li>
            }
            
            
            
            @*
                <li><a href="#"> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                <li><a href="#"> <span class="pull-right">(27)</span>Albiro</a></li>
                <li><a href="#"> <span class="pull-right">(32)</span>Ronhill</a></li>
                <li><a href="#"> <span class="pull-right">(5)</span>Oddmolly</a></li>
                <li><a href="#"> <span class="pull-right">(9)</span>Boudestijn</a></li>
                <li><a href="#"> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
            *@
        </ul>
    </div>
</div><!--/brands_products-->