Models/MatHang.cs
using System.Collections.Generic;
using System.Linq;
namespace PhuKienDienThoai.Models
{
    public class MatHang
    {
        public int Id { get; set; }
        public string TenMatHang { get; set; }
        public ICollection<SanPham> SanPhames { get; set; }
        public ICollection<DanhMuc> DanhMuces { get; set; }
        public MatHang()
        {
            SanPhames = new HashSet<SanPham>();
            DanhMuces = new HashSet<DanhMuc>();
        }
    }
}

Controllers/DanhMucController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhuKienDienThoai.Data;
using X.PagedList;

namespace PhuKienDienThoai.Controllers
{
    public class DanhMucController : Controller
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing)
                context.Dispose();
            base.Dispose(true);
        }
        ApplicationDbContext context;
        public DanhMucController(ApplicationDbContext _context) => context = _context;
        [HttpGet("[Controller]/{id:int}")]
        public async Task<IActionResult> Index(int id, int? page)
        {
            var data = await context.SanPham
                                    .Include(x => x.DanhMuc)
                                    .Where(x => x.DanhMuc.Id == id)
                                    .ToListAsync();
            var DanhMuc = await context.DanhMuc.FindAsync(id);
            var MatHang = await context.MatHang.FindAsync(DanhMuc.MatHangId);
            ViewData["SubTitle"] = MatHang.TenMatHang;
            ViewData["HeadTitle"] = DanhMuc.TenDanhMuc;
            ViewData["Title"] = ViewData["SubTitle"] + " cho sản phẩm " + ViewData["HeadTitle"];

            var model = data.ToPagedList(page ?? 1, 9);
            return View("Views/Home/Index.cshtml", model);
            // return View("Views/Home/Index.cshtml",data);
        }
        [Route("[Controller]/[Action]")]
        public async Task<IActionResult> SanPhamGiamGia(int? page)
        {
            var data = await context.SanPham.Where(x => x.PhanTramGiamGia != 0)
                                        .ToListAsync();
            ViewData["HeadTitle"] = "Sản phẩm giảm giá";
            ViewData["Title"] = "Sản phẩm giảm giá";

            var model = data.ToPagedList(page ?? 1, 9);
            return View("Views/Home/Index.cshtml", model);
            // return View("Views/Home/Index.cshtml",data);
        }

    }
}

Views/Shared/Components/MatHang/Default.cshtml
@using PhuKienDienThoai.Models
@model List<MatHang>
<h2 class="title text-center"><span class="text-block">Mặt hàng</span></h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a asp-action="SanPhamGiamGia" asp-controller="DanhMuc">Sản phẩm giảm giá</a></h4>
        </div>
    </div>
    @foreach(var item in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#sidebar_MatHang_@item.Id">
                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                        @item.TenMatHang
                    </a>
                </h4>
            </div>
            <div id="sidebar_MatHang_@item.Id" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                      
                        @{
                            var key = 0;
                            var DanhMucGroup = item.DanhMuces.Where(p => p.MatHangId == item.Id).OrderBy(p => p.TenDanhMuc);
                            foreach(var danhmuc in DanhMucGroup)
                            {
                                <li><a asp-action="Index" asp-route-id="@danhmuc.Id" asp-controller="DanhMuc">@danhmuc.TenDanhMuc</a></li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    }
</div>